name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    defaults:
      run:
        shell: bash
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: 3.10
          poetry-version: 1.7.1

      - name: Build Executable
        run: |
          poetry run python build.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-windows-latest
          path: dist/windows
      - uses: actions/download-artifact@v3
        with:
          name: build-macos-latest
          path: dist/macos

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: |
            dist/windows/*
            dist/macos/*
            