name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: "3.10"
          poetry-version: "1.7.1"

      - name: Build Executable
        run: |
          poetry run python build.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: "3.10"
          poetry-version: "1.7.1"

      - name: Extract Version
        id: extract_version
        run: |
          version=$(poetry version -s)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-windows-latest
          path: dist/windows
      - uses: actions/download-artifact@v3
        with:
          name: build-macos-latest
          path: dist/macos

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: v${{ env.VERSION }}
          releaseName: Release v${{ env.VERSION }}
          generateReleaseNotes: true
          artifacts: |
            dist/windows/*
            dist/macos/*
            