name: Trigger Webhook

on:
  push:
    branches:
      - web

jobs:
  webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Webhook
      run: |
        curl -X POST \
        -H "Content-Type: application/json" \
        -d '{"ref": "${{ github.ref }}", "after": "${{ github.sha }}"}' \
        http://elliottsf.eu.pythonanywhere.com/pull
